---
details:
  - analysis: variant2
    genome_build: hg19
    algorithm:
      aligner: bwa
      mark_duplicates: true
      recalibrate: gatk
      realign: gatk
      variantcaller: gatk-haplotype
      platform: illumina
      quality_format: Standard
      coverage_interval: exome
